<?php
/*
* Table Definition for Ingrediente - Colombina
*/


class DataObjects_Modelo extends DB_DataObject {

    // you can define these yourself
    
    var $__table='bmw_modelo';                       // table name
    var $idModelo;                              // int primary_key
    var $nombre;                              // string
    
    // these are usefull to be consistant with a autogenerated file.
    
    function staticGet($k,$v=NULL) { return DB_DataObject::staticGet('DataObjects_Modelo',$k,$v); }

  
    // now define your table structure.
    // key is column name, value is type
    function table() {
        return array(
            'idModelo'     => DB_DATAOBJECT_INT,
            'nombre'   => DB_DATAOBJECT_STR,
        );
    }
    
    // now define the keys.
    function keys() {
        return array('idModelo');
    }  
}





?>