<?php
/*
* Table Definition for Ingrediente - Colombina
*/


class DataObjects_Usuario extends DB_DataObject {

    // you can define these yourself
    
    var $__table='bmw_usuario';                      // table name
    var $idUsuario;                              // int primary_key
    var $nombre;                                 // varchar
    var $cedula;                                 // bigint
    var $email;                                  // varchar
    var $idLinea;                                // int 
    var $idModelo;                               // int
    var $idDepto;                                // int
    var $idCiudad;                               // int
    var $destino;                                // varchar
    var $hotel;                                  // varchar
    var $fecha;                                  // date
    var $placa;                                  // placa
    
    // these are usefull to be consistant with a autogenerated file.
    
    function staticGet($k,$v=NULL) { return DB_DataObject::staticGet('DataObjects_Usuario',$k,$v); }

  
    // now define your table structure.
    // key is column name, value is type
    function table() {
        return array(
            'idUsuario'     => DB_DATAOBJECT_INT,
            'nombre'   => DB_DATAOBJECT_STR,
            'cedula'     => DB_DATAOBJECT_INT,
            'email'     => DB_DATAOBJECT_STR,
            'idLinea'     => DB_DATAOBJECT_INT,
            'idModelo'     => DB_DATAOBJECT_INT,
            'idDepto'     => DB_DATAOBJECT_INT,
            'idCiudad'     => DB_DATAOBJECT_INT,
            'destino'     => DB_DATAOBJECT_STR,
            'hotel'     => DB_DATAOBJECT_STR,
            'fecha'     => DB_DATAOBJECT_STR + DB_DATAOBJECT_DATE + DB_DATAOBJECT_TIME,
            'placa'   => DB_DATAOBJECT_STR,
        );
    }
    
    // now define the keys.
    function keys() {
        return array('idUsuario');
    }  
}





?>